import logging
from functools import partial, lru_cache

import re
import ida_bytes
import ida_hexrays
import ida_name
import ida_typeinf
import ida_nalt
import ida_xref
import ida_idaapi
import idaapi
import idautils
import idc
from ida_idaapi import BADADDR
from . import utils
from .utils import batchmode

VTABLE_UNION_KEYWORD = "VTABLES"
VTABLES_UNION_VTABLE_FIELD_POSTFIX = ""
VTABLE_DELIMITER = "::"
VTABLE_POSTFIX = ida_typeinf.VTBL_SUFFIX
VTABLE_FIELD_NAME = ida_typeinf.VTBL_MEMNAME
VTABLE_INSTANCE_DELIMITER = VTABLE_DELIMITER
VTABLE_INSTANCE_KEYWORD = "vftable"
VTABLE_INSTANCE_POSTFIX = VTABLE_INSTANCE_DELIMITER + VTABLE_INSTANCE_KEYWORD
MF_BASECLASS = 0x400
PURE_VIRTUAL_NAME = '__cxa_pure_virtual'
AUTOGENERATED_FUNC_NAME_RE = re.compile(r"^(null)?v?sub_[A-F0-9]+(_[0-9]+)?$")
AUTOGENERATED_MEMBER_NAME_RE = re.compile(r"^field_[0-9A-F]+$", re.IGNORECASE)


def is_autogenerated_func_name(name):
    return AUTOGENERATED_FUNC_NAME_RE.match(name) is not None


def is_autogenerated_member_name(name):
    """Check if a member name is auto-generated by IDA (e.g., 'field_XX' when empty string is entered)."""
    return AUTOGENERATED_MEMBER_NAME_RE.match(name) is not None


def can_rename_func(name):
    return not (name.startswith("nullsub_") or name.startswith("ret_") or ("cxa_pure_virtual" in name))


def should_rename_member(name):
    return not can_rename_func(name)


def get_vtable_instance_name(class_name, parent_name=None):
    name = class_name + VTABLE_INSTANCE_POSTFIX
    if parent_name is not None:
        name += VTABLE_INSTANCE_DELIMITER + parent_name
    return name


def get_base_member_name(parent_name, offset):
    return "%s_%X" % (parent_name, offset)


def get_vtable_line(ea, stop_ea=None, ignore_list=None, pure_virtual_name=PURE_VIRTUAL_NAME):
    if stop_ea is not None and ea >= stop_ea:
        return None, 0
    if ignore_list is None:
        ignore_list = []
    func_ea = utils.get_ptr(ea)
    if func_ea in ignore_list:
        return None, 0
    is_pure_func = pure_virtual_name is not None and idc.GetDisasm(ea).endswith(pure_virtual_name)
    if not is_pure_func:
        if not utils.is_func(func_ea):
            func_ea -= 1 # ARM: function pointers point to func_start+1
        if not utils.is_func(func_ea):
            return None, 0
    return func_ea, ea + utils.WORD_LEN


def is_valid_vtable_name(member_name):
    return VTABLE_FIELD_NAME in member_name


def is_valid_vtable_type(member, member_type):
    if member_type.is_ptr():
        struct = utils.deref_struct_from_tinfo(member_type)
        return is_struct_vtable(struct)
    return False


def is_member_vtable(member):
    member_type = utils.get_member_tinfo(member)
    if not member_type or not isinstance(member_type, ida_typeinf.tinfo_t):
        return False
    if not is_valid_vtable_name(member.name):
        return False
    if not is_valid_vtable_type(member, member_type):
        return False
    return True


def is_struct_vtable(struct: ida_typeinf.tinfo_t):
    if struct is None:
        return False
    struct_name = struct.get_type_name()
    return VTABLE_POSTFIX in struct_name


def is_vtables_union(union):
    if union is None:
        return False
    if not union.is_union():
        return False
    union = ida_typeinf.tinfo_t()
    union_name = union.get_type_name()
    return is_vtables_union_name(union_name)


def is_vtables_union_name(union_name):
    return union_name.endswith(VTABLE_UNION_KEYWORD)


def find_vtable_at_offset(struct_ptr: ida_typeinf.tinfo_t, vtable_offset: int):
    current_struct = struct_ptr
    current_offset = 0
    _, member = struct_ptr.get_udm_by_offset(vtable_offset)
    if member is None:
        return None
    parents_vtables_classes = []
    current_offset += member.offset
    while current_offset < vtable_offset and member is not None:
        current_struct = utils.get_member_substruct(member)
        if current_struct is None:
            return None
        parents_vtables_classes.append(
            [
                current_struct.get_type_name(),
                vtable_offset - current_offset,
            ]
        )
        _, member = current_struct.get_udm_by_offset(vtable_offset - current_offset)
        if member is None:
            logging.exception(
                "Couldn't find vtable at offset %d for %d",
                vtable_offset - current_offset,
                struct_ptr.get_tid(),
            )
        current_offset += member.offset

    if current_offset != vtable_offset:
        return None

    while member is not None:
        if is_member_vtable(member):
            return member, current_struct, parents_vtables_classes
        current_struct = utils.get_member_substruct(member)
        if current_struct is None:
            return None
        parents_vtables_classes.append(
            [current_struct.get_type_name(), 0]
        )
        index, member = current_struct.get_udm(0)

    return None


def get_class_vtable_struct_name(class_name, vtable_offset_in_class):
    if vtable_offset_in_class == 0:
        return class_name + VTABLE_POSTFIX
    return "%s_%04X%s" % (class_name, vtable_offset_in_class, VTABLE_POSTFIX)


def get_class_vtable_field_name(class_name):
    return VTABLE_FIELD_NAME


def get_class_vtables_union_name(class_name):
    return class_name + VTABLE_DELIMITER + VTABLE_UNION_KEYWORD


def get_class_vtables_field_name(child_name):
    return child_name + VTABLES_UNION_VTABLE_FIELD_POSTFIX


def get_interface_empty_vtable_name():
    return "INTERFACE"


def install_vtables_union(
    class_name: str,
    class_vtable_member: ida_typeinf.udm_t=None,
    vtable_member_tinfo: ida_typeinf.tinfo_t=None,
    offset=0
):
    logging.debug(
        "install_vtables_union(%s, %s, %s)",
        class_name,
        class_vtable_member,
        str(vtable_member_tinfo),
    )
    if class_vtable_member and vtable_member_tinfo:
        old_vtable_sptr = utils.extract_struct_from_tinfo(vtable_member_tinfo)
        old_vtable_class_name = old_vtable_sptr.get_type_name()
    else:
        old_vtable_class_name = get_class_vtable_struct_name(class_name, offset)
        old_vtable_sptr = utils.get_sptr_by_name(old_vtable_class_name)
    vtables_union_name = old_vtable_class_name
    if old_vtable_sptr and (0 != old_vtable_sptr.rename_type(old_vtable_class_name + "_orig")):
        logging.exception(
            f"Failed changing {old_vtable_class_name}->"
            f"{old_vtable_class_name+'_orig'}"
        )
        # FIXME: why -1 and not None?
        return -1
    vtables_union_id = utils.get_or_create_struct_id(vtables_union_name, True)
    vtable_member_tinfo = utils.get_typeinf(old_vtable_class_name + "_orig")
    if vtables_union_id == BADADDR:
        logging.exception(
            "Cannot create union vtable for %s()%s",
            class_name,
            vtables_union_name,
        )
        # FIXME: why -1 and not None?
        return -1

    vtables_union = ida_typeinf.tinfo_t(tid=vtables_union_id)
    if not vtables_union:
        logging.exception("Could retrieve vtables union for %s", class_name)
        # FIXME: return -1?
    if vtable_member_tinfo is not None:
        vtables_union_vtable_field_name = get_class_vtables_field_name(class_name)
    else:
        vtables_union_vtable_field_name = get_interface_empty_vtable_name()
    utils.add_to_struct(vtables_union, vtables_union_vtable_field_name, vtable_member_tinfo)
    parent_struct = utils.get_sptr_by_name(class_name)
    flag = ida_bytes.FF_STRUCT
    mt = ida_nalt.opinfo_t()
    mt.tid = vtables_union_id
    struct = ida_typeinf.tinfo_t(tid=vtables_union_id)
    struct_size = struct.get_size()
    vtables_union_ptr_type = utils.get_typeinf_ptr(vtables_union_name)
    if class_vtable_member:
        logging.info(f"{class_vtable_member=}, {class_vtable_member=}, {offset=}, {flag=}")
        index, mem = parent_struct.get_udm_by_offset(class_vtable_member.offset)
    else:
        index, mem = parent_struct.get_udm_by_offset(offset)
        if index == -1:
            logging.info(f"{class_name=}, {vtables_union_ptr_type=}, {offset=}, {flag=}")
            index, mem = parent_struct.add_udm(get_class_vtable_field_name(class_name), vtables_union_ptr_type, offset, flag)
    logging.info(f"{mem.name=}")
    if is_valid_vtable_name(mem.name):
        logging.info(f"{index=}, {vtables_union_ptr_type=}, {mem.type=}, {flag=}")
        ret = parent_struct.set_udm_type(index, vtables_union_ptr_type, flag | ida_typeinf.TINFO_DEFINITE)
        logging.info(f"{ret}")
        ret = parent_struct.rename_udm(index, get_class_vtable_field_name(class_name))
        logging.info(f"{ret}")
        utils.refresh_struct(parent_struct)
    return vtables_union


def add_child_vtable(parent_name, child_name, child_vtable_id, offset):
    logging.debug(
        "add_child_vtable (%s, %s, %d)",
        parent_name,
        child_name,
        child_vtable_id,
    )
    parent_struct = utils.get_sptr_by_name(parent_name)
    _, parent_vtable_member = parent_struct.get_udm_by_offset(offset)
    vtable_member_tinfo = utils.get_member_tinfo(parent_vtable_member)
    parent_vtable_struct = utils.get_sptr_by_name(get_class_vtable_struct_name(parent_name, offset))
    if parent_vtable_struct is None:
        return
    pointed_struct = utils.extract_struct_from_tinfo(vtable_member_tinfo)
    logging.debug(f"{str(pointed_struct)=}, {str(parent_vtable_struct)=} {str(parent_vtable_member)=}")
    if (
        (pointed_struct is None)
        or (not is_struct_vtable(pointed_struct))
        or (parent_vtable_struct.get_tid() != pointed_struct.get_tid())
    ):
        parent_vtable_member = None
        logging.debug("Not a struct vtable: %s", str(vtable_member_tinfo))

    # TODO: Check that struct is a valid vtable by name
    #if not parent_vtable_struct.is_union():
    #    XXX obsoleted by ida9's own vtable processing
    #    logging.debug("%s vtable isn't union -> unionize it!", parent_name)
    #    parent_vtable_struct = install_vtables_union(
    #        parent_name, parent_vtable_member, vtable_member_tinfo, offset
    #    )

    child_vtable_name = ida_typeinf.tinfo_t(tid=child_vtable_id).get_type_name()
    child_vtable = utils.get_typeinf(child_vtable_name)
    logging.debug(
        "add_to_struct %s %s", parent_vtable_struct.get_tid(), str(child_vtable)
    )
    if ida_typeinf.tinfo_t(tid=child_vtable_id).get_size() == 0:
        utils.add_to_struct(
            ida_typeinf.tinfo_t(tid=child_vtable_id), "dummy", None
        )
    index, new_member = utils.add_to_struct(
        parent_vtable_struct, get_class_vtables_field_name(child_name), child_vtable
    )
#    ida_xref.add_dref(
#        new_member.type.get_tid(), child_vtable_id, ida_xref.XREF_USER | ida_xref.dr_O
#    )
#    ida_xref.add_dref(new_member.id, child_vtable_id, ida_xref.XREF_USER | ida_xref.dr_O)

def update_func_name_with_class(func_ea, class_name, overwrite=False, func_name=None):
    name = idc.get_name(func_ea)
    # Skip if function name cannot be renamed (e.g., nullsub_)
    if not can_rename_func(name):
        return name, False
    
    if is_autogenerated_func_name(name):
        if func_name is not None:
            name = func_name
        new_name = class_name + VTABLE_DELIMITER + name
        return utils.set_func_name(func_ea, new_name), True
    if overwrite:
        if (demangled := ida_name.demangle_name(name, idaapi.MNG_SHORT_FORM)):
            # 'sentry::Sentry::getDongleIds(sentry::DongleIdList *)' => 'getDongleIds'
            name = demangled.split("(",2)[0].split("::")[-1]
        if "::" in name: # not demangled name may have '::'
            name = name.split("::")[-1]
        if is_autogenerated_func_name(name):
            new_name = class_name + VTABLE_DELIMITER + name
            return utils.set_func_name(func_ea, new_name), True
#    if name.startswith("~"):
#        name = "dtor"
    return name, False


def update_func_this(func_ea, this_type=None, flags=ida_typeinf.TINFO_DEFINITE, overwrite=False):
    functype = None
    try:
        func_details = utils.get_func_details(func_ea)
        logging.info(f"{func_details=}")
        if func_details is None:
            return None
        cc = func_details.get_explicit_cc()
        if cc != idaapi.CM_CC_THISCALL and cc != idaapi.CM_CC_FASTCALL:
            return None
        if this_type and len(func_details) > 0:
            orig_this_type = func_details[0].type
            if not overwrite and orig_this_type.is_ptr() and orig_this_type.get_pointed_object().is_struct():
                return None
            func_details[0].name = "this"
            func_details[0].type = this_type
            functype = utils.update_func_details(func_ea, func_details, flags)
            logging.info(f"{functype=}")
    except ida_hexrays.DecompilationFailure as e:
        logging.exception("Couldn't decompile 0x%x", func_ea)
    return functype


def add_class_vtable(struct_ptr, vtable_name, offset=BADADDR, vtable_field_name=None):
    if vtable_field_name is None:
        class_name = struct_ptr.get_type_name()
        vtable_field_name = get_class_vtable_field_name(class_name)
    vtable_id = ida_typeinf.tinfo_t(name=vtable_name).get_tid()
    vtable_type_ptr = utils.get_typeinf_ptr(vtable_name)
    _, new_member = utils.add_to_struct(
        struct_ptr, vtable_field_name, vtable_type_ptr, offset, overwrite=True
    )
    if new_member is None:
        logging.warning(
            "vtable of %s couldn't added at offset 0x%X",
            str(vtable_type_ptr),
            offset,
        )
#    else:
#        ida_xref.add_dref(new_member.type.get_tid(), vtable_id, ida_xref.XREF_USER | ida_xref.dr_O)


@batchmode
def _extract_class_name_from_vtable(vtable_struct_name):
    """Extract class name from vtable struct name.
    
    Args:
        vtable_struct_name: Name of the vtable struct (e.g., "Class_vtbl" or "Class_0004_vtbl")
    
    Returns:
        Class name or None if extraction fails
    """
    if not vtable_struct_name.endswith(VTABLE_POSTFIX):
        return None
    
    class_name = vtable_struct_name[:-len(VTABLE_POSTFIX)]
    # Handle offset-based vtable names like "Class_0004_vtbl"
    # if "_" in class_name:
    #     parts = class_name.rsplit("_", 1)
    #     if len(parts) == 2 and len(parts[1]) == 4:
    #         try:
    #             int(parts[1], 16)  # Check if it's a hex offset
    #             class_name = parts[0]
    #         except ValueError:
    #             pass
    
    return class_name


def _print_operations_table(operations):
    """Print a table of operations with automatically calculated column widths.
    
    Args:
        operations: List of tuples (op_type, target, current, new, label)
    """
    if not operations:
        return
    
    # Calculate column widths from data (limit to 64 chars max)
    max_type_width = min(64, max(len(str(op[0])) for op in operations))
    max_target_width = min(64, max(len(str(op[1])) for op in operations))
    max_current_width = min(64, max(len(str(op[2])) for op in operations))
    max_new_width = min(64, max(len(str(op[3])) for op in operations))
    
    # Ensure minimum widths for readability
    max_type_width = max(max_type_width, 8)
    max_target_width = max(max_target_width, 8)
    max_current_width = max(max_current_width, 8)
    max_new_width = max(max_new_width, 8)
    
    # Print table rows
    for op_type, target, current, new, label in operations:
        # Truncate values if needed (leave 2 chars for "..")
        type_str = str(op_type)
        if len(type_str) > max_type_width:
            type_display = type_str[:max_type_width-2] + ".."
        else:
            type_display = type_str
        
        target_str = str(target)
        if len(target_str) > max_target_width:
            target_display = target_str[:max_target_width-2] + ".."
        else:
            target_display = target_str
        
        current_str = str(current)
        if len(current_str) > max_current_width:
            current_display = current_str[:max_current_width-2] + ".."
        else:
            current_display = current_str
        
        new_str = str(new)
        if len(new_str) > max_new_width:
            new_display = new_str[:max_new_width-2] + ".."
        else:
            new_display = new_str
        
        label_str = f" ({label})" if label else ""
        print(f"[.] rename  {type_display:<{max_type_width}}  {target_display:<{max_target_width}}  {current_display:<{max_current_width}} -> {new_display:<{max_new_width}}{label_str}")


def _add_vtable_member_rename(vtable_tif, member_idx, member_name, new_field_name, 
                               args_list, processed_classes, class_tid, member_offset, 
                               relation_label=""):
    """Add a vtable member rename to the args list if not already processed.
    
    Args:
        vtable_tif: tinfo_t of the vtable struct
        member_idx: Index of the member in the vtable
        member_name: Current name of the member
        new_field_name: New name for the member
        args_list: List to append rename operations to
        processed_classes: Set of (class_tid, offset) tuples already processed
        class_tid: TID of the class this vtable belongs to
        member_offset: Offset of the member in bits
        relation_label: Optional label for the relation (e.g., "superclass", "subclass")
    
    Returns:
        True if the member was added, False if it was already processed
    """
    class_key = (class_tid, member_offset)
    if class_key in processed_classes:
        return False
    
    processed_classes.add(class_key)
    args_list.append([vtable_tif, member_idx, new_field_name])
    return True


def _process_related_class_vtable(related_class_tif, member_offset, 
                                   new_field_name, args_list, processed_classes, 
                                   relation_label, member_rename_info=None):
    """Process vtable member in a related class (superclass or subclass).
    
    Args:
        related_class_tif: tinfo_t of the class to process
        member_offset: Offset of the member in bits
        new_field_name: New name for the member
        args_list: List to append rename operations to
        processed_classes: Set of (class_tid, offset) tuples already processed
        relation_label: Label for the relation (e.g., "superclass", "subclass")
        member_rename_info: Optional list to track member renames for table display
    
    Returns:
        tuple: (vtable_tif, member_tid) if member was found, (None, None) otherwise
    """
    related_class_name = related_class_tif.get_type_name()
    related_vtable_name = get_class_vtable_struct_name(related_class_name, 0)
    related_vtable_tif = ida_typeinf.tinfo_t(name=related_vtable_name)
    
    if not related_vtable_tif.is_udt():
        return None, None
    
    related_member_idx, related_member = related_vtable_tif.get_udm_by_offset(member_offset)
    if related_member_idx != -1:
        related_class_tid = related_class_tif.get_tid()
        if _add_vtable_member_rename(
            related_vtable_tif, related_member_idx, related_member.name,
            new_field_name, args_list, processed_classes, related_class_tid,
            member_offset, relation_label
        ) and member_rename_info is not None:
            member_rename_info.append((related_vtable_tif, related_member_idx, related_member.name, new_field_name))
        
        # Return vtable and member TID for function renaming tracking
        member_tid = related_vtable_tif.get_udm_tid(related_member_idx)
        return related_vtable_tif, member_tid
    
    return None, None


def _find_sibling_classes(base_class_tif):
    """Find all classes that inherit from the given base class (siblings).
    
    Args:
        base_class_tif: tinfo_t of the base class
    
    Returns:
        list: List of tinfo_t objects for classes that inherit from base_class_tif at offset 0
    """
    siblings = []
    base_tid = base_class_tif.get_tid()
    if base_tid == BADADDR:
        return siblings
    
    for ref_sid in idautils.DataRefsTo(base_tid):
        if not idc.is_member_id(ref_sid):
            continue
        
        sibling_udm = ida_typeinf.udm_t()
        sibling_tif = ida_typeinf.tinfo_t()
        if sibling_tif.get_udm_by_tid(sibling_udm, ref_sid) == -1:
            continue
        
        # Check if this is a base class member at offset 0 matching our base class
        if (sibling_udm.is_baseclass() and sibling_udm.offset == 0 and
            sibling_udm.type.get_tid() == base_tid):
            siblings.append(sibling_tif)
    
    return siblings


def post_func_name_change(new_name, ea):
    """Handle function name change by updating related vtable struct members and functions.
    
    When a function is renamed, this function:
    1. Finds all struct members that reference this function (via data xrefs)
    2. Extracts the last part of the function name (after splitting by VTABLE_DELIMITER)
    3. Converts it to a field name and renames the struct members
    4. Also renames corresponding members in superclasses and subclasses (basic inheritance at offset 0)
    5. After renaming vtable members, also renames functions pointed by those members
    
    Args:
        new_name: The new function name (may contain VTABLE_DELIMITER like "Class::method")
        ea: The function's effective address
    
    Returns:
        tuple: (function_to_call, list_of_args) for batch processing
    """
    logging.info(f"post_func_name_change: Called with new_name={new_name}, ea={hex(ea)}")
    
    force_rename = False
    vtable_offset = None  # Initialize to None - not all classes have vtables
    # Check if new name ends with "::" and it's a virtual function
    if new_name.endswith("::"):
        vtable_offset = _find_vtable_offset_for_function(ea)
        if vtable_offset is not None:
            # Rename to vsub_XXXX where XXXX is the offset in hex
            new_name = funcname2fieldname(new_name, vtable_offset)
            idaapi.set_name(ea, new_name, idaapi.SN_FORCE | idaapi.SN_NOCHECK)
            force_rename = True
    
    # Don't trigger renames if the new method name is autogenerated
    new_field_name = funcname2fieldname(new_name, vtable_offset)
    if is_autogenerated_func_name(new_field_name) and not force_rename:
        logging.info(f"post_func_name_change: Skipping rename propagation - new name '{new_name}' (field: '{new_field_name}') is autogenerated")
        return None, []
    
    ref_eas = idautils.DataRefsTo(ea)
    
    # Check if all data references are from existing vtable members
    # If there are references from raw data blocks (not structured as vtable), skip auto-fix
    has_non_vtable_refs = False
    for ref_ea in ref_eas:
        # Check if this is a member TID
        if not idc.is_member_id(ref_ea):
            # This is a raw data reference, not from a vtable member
            has_non_vtable_refs = True
            logging.debug(f"post_func_name_change: Found non-vtable data reference at {hex(ref_ea)}")
            break
        
        # Check if the member belongs to a vtable struct
        udm = ida_typeinf.udm_t()
        vtable_tif = ida_typeinf.tinfo_t()
        idx = vtable_tif.get_udm_by_tid(udm, ref_ea)
        if idx == -1:
            has_non_vtable_refs = True
            logging.debug(f"post_func_name_change: Could not get member details for {hex(ref_ea)}")
            break
        
        # Check if it's a vtable struct
        vtable_struct_name = vtable_tif.get_type_name()
        if not vtable_struct_name or not vtable_struct_name.endswith(VTABLE_POSTFIX):
            has_non_vtable_refs = True
            logging.debug(f"post_func_name_change: Member {hex(ref_ea)} is not from a vtable struct (struct: {vtable_struct_name})")
            break
    
    if has_non_vtable_refs:
        logging.info(f"post_func_name_change: Skipping auto-fix - function has data references not from existing vtable members")
        return None, []
    
    args_list = []
    processed_members = set()
    processed_classes = set()
    # Track vtable members we're renaming so we can rename their functions afterwards
    renamed_member_info = []  # List of (vtable_tif, member_tid, member_offset, new_field_name, class_name)
    # Track member names for table display: (vtable_tif, member_idx, current_name, new_name)
    member_rename_info = []
    
    for sid in ref_eas:
        if sid in processed_members:
            continue
        processed_members.add(sid)

        udm = ida_typeinf.udm_t()
        vtable_tif = ida_typeinf.tinfo_t()
        idx = vtable_tif.get_udm_by_tid(udm, sid)
        if idx == -1:
            continue
        
        vtable_struct_name = vtable_tif.get_type_name()
        member_offset = udm.offset
        
        # Extract class name from vtable struct name
        class_name = _extract_class_name_from_vtable(vtable_struct_name)
        
        # If we can't extract class name or get class struct, just process this member
        if not class_name:
            if _add_vtable_member_rename(vtable_tif, idx, udm.name, new_field_name,
                                         args_list, processed_classes, vtable_tif.get_tid(),
                                         member_offset):
                member_rename_info.append((vtable_tif, idx, udm.name, new_field_name))
            # Track this member for function renaming
            renamed_member_info.append((vtable_tif, sid, member_offset, new_field_name, None))
            continue
        
        class_tif = ida_typeinf.tinfo_t(name=class_name)
        if not class_tif.is_udt():
            if _add_vtable_member_rename(vtable_tif, idx, udm.name, new_field_name,
                                         args_list, processed_classes, vtable_tif.get_tid(),
                                         member_offset):
                member_rename_info.append((vtable_tif, idx, udm.name, new_field_name))
            renamed_member_info.append((vtable_tif, sid, member_offset, new_field_name, None))
            continue
        
        class_tid = class_tif.get_tid()
        if class_tid == BADADDR:
            if _add_vtable_member_rename(vtable_tif, idx, udm.name, new_field_name,
                                         args_list, processed_classes, vtable_tif.get_tid(),
                                         member_offset):
                member_rename_info.append((vtable_tif, idx, udm.name, new_field_name))
            renamed_member_info.append((vtable_tif, sid, member_offset, new_field_name, None))
            continue
        
        # Process the original member
        if _add_vtable_member_rename(vtable_tif, idx, udm.name, new_field_name,
                                     args_list, processed_classes, class_tid,
                                     member_offset):
            member_rename_info.append((vtable_tif, idx, udm.name, new_field_name))
        
        # Track this member for function renaming
        renamed_member_info.append((vtable_tif, sid, member_offset, new_field_name, class_name))
        
        # Find and process superclasses (base classes at offset 0)
        for base_udm in class_tif.iter_udt():
            if base_udm.is_baseclass() and base_udm.offset == 0:
                base_class_tif = base_udm.type
                base_class_name = base_class_tif.get_type_name()
                _process_related_class_vtable(
                    base_class_tif, member_offset, new_field_name,
                    args_list, processed_classes, "superclass", member_rename_info
                )
                # Track superclass member for function renaming
                base_vtable_name = get_class_vtable_struct_name(base_class_name, 0)
                base_vtable_tif = ida_typeinf.tinfo_t(name=base_vtable_name)
                if base_vtable_tif.is_udt():
                    base_member_idx, base_member = base_vtable_tif.get_udm_by_offset(member_offset)
                    if base_member_idx != -1:
                        base_member_tid = base_vtable_tif.get_udm_tid(base_member_idx)
                        if base_member_tid != BADADDR:
                            renamed_member_info.append((base_vtable_tif, base_member_tid, member_offset, new_field_name, base_class_name))
                            logging.debug(f"post_func_name_change: Tracked superclass member {hex(base_member_tid)} in {base_vtable_name}")
                
                # Find and process sibling classes (classes that share the same base class)
                # sibling_classes = _find_sibling_classes(base_class_tif)
                # for sibling_tif in sibling_classes:
                #     sibling_name = sibling_tif.get_type_name()
                #     sibling_tid = sibling_tif.get_tid()
                #     # Skip the current class itself (already processed)
                #     if sibling_tid == class_tid:
                #         continue
                #     _process_related_class_vtable(
                #         sibling_tif, member_offset, new_field_name,
                #         args_list, processed_classes, "sibling", member_rename_info
                #     )
                #     # Track sibling member for function renaming
                #     sibling_vtable_name = get_class_vtable_struct_name(sibling_name, 0)
                #     sibling_vtable_tif = ida_typeinf.tinfo_t(name=sibling_vtable_name)
                #     if sibling_vtable_tif.is_udt():
                #         sibling_member_idx, sibling_member = sibling_vtable_tif.get_udm_by_offset(member_offset)
                #         if sibling_member_idx != -1:
                #             sibling_member_tid = sibling_vtable_tif.get_udm_tid(sibling_member_idx)
                #             if sibling_member_tid != BADADDR:
                #                 renamed_member_info.append((sibling_vtable_tif, sibling_member_tid, member_offset, new_field_name, sibling_name))
                #                 logging.debug(f"post_func_name_change: Tracked sibling member {hex(sibling_member_tid)} in {sibling_vtable_name}")
        
        # Find and process subclasses (classes that inherit from this class at offset 0)
        base_tid = class_tif.get_tid()
        for ref_sid in idautils.DataRefsTo(base_tid):
            if not idc.is_member_id(ref_sid):
                continue
            
            subclass_udm = ida_typeinf.udm_t()
            subclass_tif = ida_typeinf.tinfo_t()
            if subclass_tif.get_udm_by_tid(subclass_udm, ref_sid) == -1:
                continue
            
            # Check if this is a base class member at offset 0 matching our class
            if (subclass_udm.is_baseclass() and subclass_udm.offset == 0 and
                subclass_udm.type.get_tid() == base_tid):
                subclass_name = subclass_tif.get_type_name()
                _process_related_class_vtable(
                    subclass_tif, member_offset, new_field_name,
                    args_list, processed_classes, "subclass", member_rename_info
                )
                # Track subclass member for function renaming
                subclass_vtable_name = get_class_vtable_struct_name(subclass_name, 0)
                subclass_vtable_tif = ida_typeinf.tinfo_t(name=subclass_vtable_name)
                if subclass_vtable_tif.is_udt():
                    subclass_member_idx, subclass_member = subclass_vtable_tif.get_udm_by_offset(member_offset)
                    if subclass_member_idx != -1:
                        subclass_member_tid = subclass_vtable_tif.get_udm_tid(subclass_member_idx)
                        if subclass_member_tid != BADADDR:
                            renamed_member_info.append((subclass_vtable_tif, subclass_member_tid, member_offset, new_field_name, subclass_name))
                            logging.debug(f"post_func_name_change: Tracked subclass member {hex(subclass_member_tid)} in {subclass_vtable_name}")

    # Collect all operations to print in a table
    operations = []
    
    # Collect vtable member renames from tracked info
    for vtable_tif, member_idx, current_name, new_name in member_rename_info:
        vtable_name = vtable_tif.get_type_name()
        operations.append(("vtable member", vtable_name, current_name or f"member_{member_idx}", new_name, ""))
    
    # Collect function renames (preview what will be renamed)
    processed_func_eas_preview = set([ea])  # Track original function
    for vtable_tif, member_tid, member_offset, field_name, class_name in renamed_member_info:
        # Get functions for this member
        func_eas = _get_function_eas_from_vtable_member(member_tid, vtable_tif, member_offset)
        
        # Preview function renames (preserve prefix)
        for func_ea in func_eas:
            if func_ea in processed_func_eas_preview:
                continue
            processed_func_eas_preview.add(func_ea)
            
            current_name = idc.get_name(func_ea)
            # Skip if function name cannot be renamed (e.g., nullsub_)
            if not can_rename_func(current_name):
                continue
            
            # Preserve prefix when previewing - only change part after '::'
            func_name = preserve_prefix_rename_func(current_name, field_name)
            if current_name != func_name:
                operations.append(("function", hex(func_ea), current_name, func_name, ""))
    
    # Print table
    if operations:
        _print_operations_table(operations)
    
    # After renaming vtable members, rename functions they point to
    # We need to do this after the members are renamed, so we'll return a wrapper function
    def rename_members_and_functions():
        logging.info(f"post_func_name_change: rename_members_and_functions called, will rename {len(args_list)} vtable member(s)")
        # First rename all vtable members
        for args in args_list:
            logging.debug(f"post_func_name_change: Renaming vtable member with args: {args}")
            utils.set_member_name(*args)
        
        # Then rename functions pointed by those members
        logging.info(f"post_func_name_change: Processing {len(renamed_member_info)} renamed member(s) to rename their functions")
        processed_func_eas = set([ea])  # Track original function to avoid loops
        for vtable_tif, member_tid, member_offset, field_name, class_name in renamed_member_info:
            logging.debug(f"post_func_name_change: Processing member {hex(member_tid)} in {vtable_tif.get_type_name()}, field_name={field_name}, class_name={class_name}")
            # Get functions for this member
            func_eas = _get_function_eas_from_vtable_member(member_tid, vtable_tif, member_offset)
            logging.debug(f"post_func_name_change: Found {len(func_eas)} function(s) for member {hex(member_tid)}")
            
            # Rename functions (skip if already processed or already has correct name)
            for func_ea in func_eas:
                if func_ea in processed_func_eas:
                    continue
                processed_func_eas.add(func_ea)
                
                current_name = idc.get_name(func_ea)
                # Skip if function name cannot be renamed (e.g., nullsub_)
                if not can_rename_func(current_name):
                    logging.debug(f"post_func_name_change: Function {hex(func_ea)} has name '{current_name}' that cannot be renamed, skipping")
                    continue
                
                # Preserve prefix when renaming - only change part after '::'
                func_name = preserve_prefix_rename_func(current_name, field_name)
                
                if current_name == func_name:
                    logging.debug(f"post_func_name_change: Function {hex(func_ea)} already has name '{func_name}', skipping")
                    continue
                
                utils.set_func_name(func_ea, func_name)
                logging.info(f"post_func_name_change: Renamed function {hex(func_ea)} from '{current_name}' to '{func_name}'")
    
    return rename_members_and_functions, [()]


def post_struct_member_name_change(udt_name, udm, new_name, old_name=None):
    """Handle vtable struct member name change by updating related functions and members.
    
    When a vtable struct member is renamed, this function:
    1. Finds all functions referenced by this member (via data xrefs, comments, or vtable instances)
    2. Converts the new field name to a function name
    3. Returns a list of operations to rename all related functions and members
    4. Also processes corresponding functions and members in superclasses and subclasses (basic inheritance at offset 0)
    
    Args:
        udt_name: The UDT (struct) name
        udm: The udm_t object representing the member
        new_name: The new member name (field name)
        old_name: The old member name (optional, used to detect if user cleared the name)
    
    Returns:
        tuple: (function_to_call, list_of_args) for batch processing
    """
    logging.info(f"post_struct_member_name_change: Called with udt_name={udt_name}, new_name={new_name}, old_name={old_name}")
    
    force_rename = False
    if is_autogenerated_member_name(new_name):
        # Get the vtable struct
        struct_tid = idc.get_struc_id(udt_name)
        if struct_tid != BADADDR:
            struct_name = idc.get_struc_name(struct_tid)
            # Check if this is a vtable struct by checking if it ends with VTABLE_POSTFIX
            if struct_name and struct_name.endswith(VTABLE_POSTFIX):
                # Extract offset from "field_XX" -> "XX"
                # The pattern is "field_" followed by hex digits
                offset_str = new_name.replace("field_", "")
                try:
                    # Convert hex string to int, then format as hex with proper case
                    offset_val = int(offset_str, 16)
                    new_member_name = f"vsub_{offset_val:04X}"
                    # Rename the member
                    vtable_tif = ida_typeinf.tinfo_t(tid=struct_tid)
                    member_offset_bytes = udm.offset // 8
                    member_idx, _ = vtable_tif.get_udm_by_offset(member_offset_bytes * 8)
                    if member_idx != -1:
                        vtable_tif.rename_udm(member_idx, new_member_name)
                        # Update new_name to continue with normal rename propagation
                        new_name = new_member_name
                        # Update udm.name to reflect the new name
                        udm.name = new_member_name
                        force_rename = True
                except ValueError:
                    pass
    
    # Don't trigger renames if the new method name is autogenerated
    if is_autogenerated_func_name(new_name) and not force_rename:
        logging.info(f"post_struct_member_name_change: Skipping rename propagation - new name '{new_name}' is autogenerated")
        return None, []
    
    # Get struct TID from UDT name
    struct_tid = idc.get_struc_id(udt_name)
    if struct_tid == BADADDR:
        logging.warning(f"post_struct_member_name_change: Invalid struct_tid for {udt_name}")
        return None, []
    
    # Get member TID from struct TID and member offset
    member_offset_bytes = udm.offset // 8
    member_tid = idc.get_member_id(struct_tid, member_offset_bytes)
    if member_tid == BADADDR or member_tid == -1:
        logging.warning(f"post_struct_member_name_change: Invalid member_tid for struct {udt_name} at offset {member_offset_bytes}")
        return None, []
    
    # Get the vtable struct and member details using get_udm_by_tid
    vtable_tif = ida_typeinf.tinfo_t()
    idx = vtable_tif.get_udm_by_tid(ida_typeinf.udm_t(), member_tid)
    if idx == -1:
        logging.warning(f"post_struct_member_name_change: Could not get member details for member_tid={hex(member_tid)}")
        return None, []
    
    # Only process vtable structs (structs ending with VTABLE_POSTFIX)
    vtable_struct_name = vtable_tif.get_type_name()
    if not vtable_struct_name.endswith(VTABLE_POSTFIX):
        logging.debug(f"post_struct_member_name_change: Skipping non-vtable struct {vtable_struct_name}")
        return None, []
    
    member_offset = udm.offset
    current_member_name = udm.name or f"member_{idx}"
    
    # Get all function EAs referenced by this member (for function renaming later)
    func_eas = _get_function_eas_from_vtable_member(member_tid, vtable_tif, member_offset)
    
    # Only process the specific member that was renamed, NOT all members that reference the same function
    # This prevents renaming other members in the same vtable that happen to point to the same function
    args_list = []
    processed_classes = set()
    renamed_member_info = []  # List of (vtable_tif, member_tid, member_offset, new_field_name, class_name)
    member_rename_info = []  # List of (vtable_tif, member_idx, current_name, new_name)
    
    # Extract class name from vtable struct name
    member_class_name = _extract_class_name_from_vtable(vtable_struct_name)
    
    # Process the specific member that was renamed
    if not member_class_name:
        # If we can't extract class name, just process this member
        if _add_vtable_member_rename(vtable_tif, idx, current_member_name, new_name,
                                     args_list, processed_classes, vtable_tif.get_tid(),
                                     member_offset):
            member_rename_info.append((vtable_tif, idx, current_member_name, new_name))
        # Track this member for function renaming
        renamed_member_info.append((vtable_tif, member_tid, member_offset, new_name, None))
    else:
        member_class_tif = ida_typeinf.tinfo_t(name=member_class_name)
        if not member_class_tif.is_udt():
            if _add_vtable_member_rename(vtable_tif, idx, current_member_name, new_name,
                                         args_list, processed_classes, vtable_tif.get_tid(),
                                         member_offset):
                member_rename_info.append((vtable_tif, idx, current_member_name, new_name))
            renamed_member_info.append((vtable_tif, member_tid, member_offset, new_name, None))
        else:
            member_class_tid = member_class_tif.get_tid()
            if member_class_tid == BADADDR:
                if _add_vtable_member_rename(vtable_tif, idx, current_member_name, new_name,
                                             args_list, processed_classes, vtable_tif.get_tid(),
                                             member_offset):
                    member_rename_info.append((vtable_tif, idx, current_member_name, new_name))
                renamed_member_info.append((vtable_tif, member_tid, member_offset, new_name, None))
            else:
                # Process the specific member that was renamed
                if _add_vtable_member_rename(vtable_tif, idx, current_member_name, new_name,
                                             args_list, processed_classes, member_class_tid,
                                             member_offset):
                    member_rename_info.append((vtable_tif, idx, current_member_name, new_name))
                
                # Track this member for function renaming
                renamed_member_info.append((vtable_tif, member_tid, member_offset, new_name, member_class_name))
                
                # Find and process siblings of the current class (classes that share the same base classes)
                # This ensures we rename in all sibling classes, not just siblings of direct base
                for base_udm in member_class_tif.iter_udt():
                    if base_udm.is_baseclass() and base_udm.offset == 0:
                        base_class_tif = base_udm.type
                        sibling_classes = _find_sibling_classes(base_class_tif)
                        for sibling_tif in sibling_classes:
                            sibling_name = sibling_tif.get_type_name()
                            sibling_tid = sibling_tif.get_tid()
                            # Skip the current class itself (already processed)
                            if sibling_tid == member_class_tid:
                                continue
                            # Process vtable member in sibling at the SAME OFFSET
                            sibling_vtable_tif, sibling_member_tid = _process_related_class_vtable(
                                sibling_tif, member_offset, new_name,
                                args_list, processed_classes, "sibling", member_rename_info
                            )
                            # Track sibling member for function renaming
                            if sibling_vtable_tif is not None and sibling_member_tid != BADADDR:
                                renamed_member_info.append((sibling_vtable_tif, sibling_member_tid, member_offset, new_name, sibling_name))
                
                # Find and process superclasses (base classes at offset 0) - recursively
                def process_base_class_recursive(class_tif, processed_bases):
                    """Recursively process all base classes and their siblings."""
                    class_tid = class_tif.get_tid()
                    if class_tid == BADADDR or class_tid in processed_bases:
                        return
                    processed_bases.add(class_tid)
                    
                    for base_udm in class_tif.iter_udt():
                        if base_udm.is_baseclass() and base_udm.offset == 0:
                            base_class_tif = base_udm.type
                            base_class_name = base_class_tif.get_type_name()
                            # Process vtable member in superclass at the SAME OFFSET
                            base_vtable_tif, base_member_tid = _process_related_class_vtable(
                                base_class_tif, member_offset, new_name,
                                args_list, processed_classes, "superclass", member_rename_info
                            )
                            # Track superclass member for function renaming
                            if base_vtable_tif is not None and base_member_tid != BADADDR:
                                renamed_member_info.append((base_vtable_tif, base_member_tid, member_offset, new_name, base_class_name))
                            
                            # Find and process sibling classes (classes that share the same base class)
                            sibling_classes = _find_sibling_classes(base_class_tif)
                            for sibling_tif in sibling_classes:
                                sibling_name = sibling_tif.get_type_name()
                                sibling_tid = sibling_tif.get_tid()
                                # Skip the current class itself (already processed)
                                if sibling_tid == member_class_tid:
                                    continue
                                # Process vtable member in sibling at the SAME OFFSET
                                sibling_vtable_tif, sibling_member_tid = _process_related_class_vtable(
                                    sibling_tif, member_offset, new_name,
                                    args_list, processed_classes, "sibling", member_rename_info
                                )
                                # Track sibling member for function renaming
                                if sibling_vtable_tif is not None and sibling_member_tid != BADADDR:
                                    renamed_member_info.append((sibling_vtable_tif, sibling_member_tid, member_offset, new_name, sibling_name))
                            
                            # Recursively process parent classes
                            process_base_class_recursive(base_class_tif, processed_bases)
                
                processed_bases = set()
                process_base_class_recursive(member_class_tif, processed_bases)
                
                # Find and process subclasses (classes that inherit from this class at offset 0)
                base_tid = member_class_tif.get_tid()
                for ref_sid in idautils.DataRefsTo(base_tid):
                    if not idc.is_member_id(ref_sid):
                        continue
                    
                    subclass_udm = ida_typeinf.udm_t()
                    subclass_tif = ida_typeinf.tinfo_t()
                    if subclass_tif.get_udm_by_tid(subclass_udm, ref_sid) == -1:
                        continue
                    
                    # Check if this is a base class member at offset 0 matching our class
                    if (subclass_udm.is_baseclass() and subclass_udm.offset == 0 and
                        subclass_udm.type.get_tid() == base_tid):
                        subclass_name = subclass_tif.get_type_name()
                        # Process vtable member in subclass at the SAME OFFSET
                        subclass_vtable_tif, subclass_member_tid = _process_related_class_vtable(
                            subclass_tif, member_offset, new_name,
                            args_list, processed_classes, "subclass", member_rename_info
                        )
                        # Track subclass member for function renaming
                        if subclass_vtable_tif is not None and subclass_member_tid != BADADDR:
                            renamed_member_info.append((subclass_vtable_tif, subclass_member_tid, member_offset, new_name, subclass_name))
    
    # Collect all operations to print in a table (same as post_func_name_change)
    operations = []
    
    # Collect vtable member renames from tracked info
    for vtable_tif, member_idx, current_name, new_name in member_rename_info:
        vtable_name = vtable_tif.get_type_name()
        operations.append(("vtable member", vtable_name, current_name or f"member_{member_idx}", new_name, ""))
    
    # Collect function renames (preview what will be renamed)
    processed_func_eas_preview = set()
    for vtable_tif, member_tid, member_offset, field_name, class_name in renamed_member_info:
        # Get functions for this member
        func_eas = _get_function_eas_from_vtable_member(member_tid, vtable_tif, member_offset)
        
        # Preview function renames (preserve prefix)
        for func_ea in func_eas:
            if func_ea in processed_func_eas_preview:
                continue
            processed_func_eas_preview.add(func_ea)
            
            current_name = idc.get_name(func_ea)
            # Skip if function name cannot be renamed (e.g., nullsub_)
            if not can_rename_func(current_name):
                continue
            
            # Preserve prefix when previewing - only change part after '::'
            func_name = preserve_prefix_rename_func(current_name, field_name)
            if current_name != func_name:
                operations.append(("function", hex(func_ea), current_name, func_name, ""))
    
    # Print table
    if operations:
        _print_operations_table(operations)
    
    # After renaming vtable members, rename functions they point to
    # We need to do this after the members are renamed, so we'll return a wrapper function
    def rename_members_and_functions():
        logging.info(f"post_struct_member_name_change: rename_members_and_functions called, will rename {len(args_list)} vtable member(s)")
        # First rename all vtable members
        for args in args_list:
            logging.debug(f"post_struct_member_name_change: Renaming vtable member with args: {args}")
            utils.set_member_name(*args)
        
        # Then rename functions pointed by those members
        logging.info(f"post_struct_member_name_change: Processing {len(renamed_member_info)} renamed member(s) to rename their functions")
        processed_func_eas = set()
        for vtable_tif, member_tid, member_offset, field_name, class_name in renamed_member_info:
            logging.debug(f"post_struct_member_name_change: Processing member {hex(member_tid)} in {vtable_tif.get_type_name()}, field_name={field_name}, class_name={class_name}")
            # Get functions for this member
            func_eas = _get_function_eas_from_vtable_member(member_tid, vtable_tif, member_offset)
            logging.debug(f"post_struct_member_name_change: Found {len(func_eas)} function(s) for member {hex(member_tid)}")
            
            # Rename functions (skip if already processed or already has correct name)
            for func_ea in func_eas:
                if func_ea in processed_func_eas:
                    continue
                processed_func_eas.add(func_ea)
                
                current_name = idc.get_name(func_ea)
                # Skip if function name cannot be renamed (e.g., nullsub_)
                if not can_rename_func(current_name):
                    logging.debug(f"post_struct_member_name_change: Function {hex(func_ea)} has name '{current_name}' that cannot be renamed, skipping")
                    continue
                
                # Preserve prefix when renaming - only change part after '::'
                func_name = preserve_prefix_rename_func(current_name, field_name)
                
                if current_name == func_name:
                    logging.debug(f"post_struct_member_name_change: Function {hex(func_ea)} already has name '{func_name}', skipping")
                    continue
                
                utils.set_func_name(func_ea, func_name)
                logging.info(f"post_struct_member_name_change: Renamed function {hex(func_ea)} from '{current_name}' to '{func_name}'")
    
    return rename_members_and_functions, [()]


def post_struct_member_type_change(member):
    xrefs = idautils.XrefsFrom(member.type.get_tid())
    xrefs = filter(lambda x: x.type == ida_xref.dr_I and x.user == 1, xrefs)
    for xref in xrefs:
        if utils.is_func(xref.to):
            function_ptr_tinfo = utils.get_member_tinfo(member)
            if function_ptr_tinfo.is_funcptr():
                function_tinfo = function_ptr_tinfo.get_pointed_object()
                if function_tinfo is not None:
                    ida_typeinf.apply_tinfo(
                        xref.to, function_tinfo, ida_typeinf.TINFO_DEFINITE
                    )


@batchmode
def post_func_type_change(pfn):
    ea = pfn.start_ea
    xrefs = idautils.XrefsTo(ea, ida_xref.XREF_USER)
    xrefs = list(filter(lambda x: x.type == ida_xref.dr_I and x.user == 1, xrefs))
    args_list = []
    if len(xrefs) == 0:
        return None, []
    try:
        xfunc = ida_hexrays.decompile(ea)
        func_ptr_typeinf = utils.get_typeinf_ptr(xfunc.type)
        for xref in xrefs:
            member = ida_typeinf.udm_t()
            ida_typeinf.tinfo_t().get_udm_by_tid(member, xref.frm)
            struct = ida_typeinf.tinfo_t(tid=xref.frm)
            index, _ = struct.get_udm(0)
            if member is not None and struct is not None:
                args_list.append(
                    [struct, index, func_ptr_typeinf, ida_typeinf.TINFO_DEFINITE]
                )
    except Exception:
        pass
    return ida_typeinf.tinfo_t.set_udm_type, args_list


def make_funcptr_pt(func, this_type):
    return utils.get_typeinf("void (*)(%s *)" % str(this_type))


def fix_userpurge(funcea, flags=ida_typeinf.TINFO_DEFINITE):
    """@return: True if __userpurge calling conv was found and fixed at funcea, otherwise False"""
    funcea = utils.get_func_start(funcea)
    if funcea == BADADDR:
        return False
    tif = utils.get_func_tinfo(funcea)
    if not tif:
        return False
    typestr = str(tif)
    if not typestr:
        return False
    if "__userpurge" not in typestr:
        return False
    typestr = typestr.replace("__userpurge", "(__thiscall)")
    typestr = re.sub(r"\@\<\w+\>", "", typestr)
    py_type = idc.parse_decl(typestr, idc.PT_SILENT)
    if not py_type:
        logging.warn("%08X Failed to fix userpurge", funcea)
        return False
    return idc.apply_type(funcea, py_type[1:], flags)


def funcname2fieldname(name, field_offset=None):
    """Convert function name to field name.
    
    Args:
        name: Function name to convert
        field_offset: Optional field offset in bytes. If provided and should_rename_member
                     returns True, generates "vsub_XXXX" name instead.
    
    Returns:
        Field name (e.g., "getDongleIds", "dtor", or "vsub_0028" if offset provided)
    """
    # If field_offset is provided and should_rename_member returns True, generate vsub_XXXX
    if field_offset is not None and should_rename_member(name):
        return f"vsub_{field_offset:04X}"

    if (demangled := ida_name.demangle_name(name, idaapi.MNG_SHORT_FORM)):
        # 'sentry::Sentry::getDongleIds(sentry::DongleIdList *)' => 'getDongleIds'
        name = demangled.split("(",2)[0].split(VTABLE_DELIMITER)[-1]
    if "::" in name: # not demangled name may have '::' ?
        name = name.split("::")[-1]
    if name.startswith("~"):
        name = "dtor"
    if name.startswith("operator "):
        name = name[9:].strip()
    
    return name


def fieldname2funcname(field_name, class_name=None):
    """Convert field name to function name.
    
    This is the reverse of funcname2fieldname. It converts a vtable member
    field name back to a function name, optionally with class prefix.
    
    Args:
        field_name: The field name (e.g., "getDongleIds", "dtor")
        class_name: Optional class name to prefix (e.g., "MyClass")
    
    Returns:
        Function name (e.g., "MyClass::getDongleIds" or just "getDongleIds")
    """
    return field_name


def preserve_prefix_rename_func(current_name, new_field_name):
    """Rename function preserving the prefix before '::'.
    
    If the current function name has '::' in it, preserve everything
    before and including the last '::', and only change the part after.
    
    Args:
        current_name: Current function name (e.g., "Ford_AT_Component_AE::sub_6410E0")
        new_field_name: New field name to use after '::' (e.g., "process_state")
    
    Returns:
        New function name preserving prefix (e.g., "Ford_AT_Component_AE::process_state")
    """
    if VTABLE_DELIMITER in current_name:
        # Extract prefix (everything before and including the last '::')
        prefix = VTABLE_DELIMITER.join(current_name.split(VTABLE_DELIMITER)[:-1])
        if prefix:
            return prefix + VTABLE_DELIMITER + new_field_name
        else:
            return new_field_name
    else:
        # No prefix, just use the new field name
        return new_field_name


def _find_vtable_offset_for_function(func_ea):
    """Find the vtable offset for a virtual function.
    
    Uses existing xrefs from the function to vtable members to find the offset.
    
    Args:
        func_ea: EA of the function
        
    Returns:
        Offset in bytes if found, None otherwise
    """
    try:
        # Get all references TO this function (these should include vtable member TIDs)
        for member_tid in idautils.DataRefsTo(func_ea):
            # Check if this is a member TID
            if not idc.is_member_id(member_tid):
                continue
            
            # Get the member details
            udm = ida_typeinf.udm_t()
            vtable_tif = ida_typeinf.tinfo_t()
            idx = vtable_tif.get_udm_by_tid(udm, member_tid)
            if idx == -1:
                continue
            
            # Check if this is a vtable struct
            vtable_struct_name = vtable_tif.get_type_name()
            if not vtable_struct_name or ("vtbl" not in vtable_struct_name.lower() and "vtable" not in vtable_struct_name.lower()):
                continue
            
            # Found a vtable member that references this function
            # Convert offset from bits to bytes
            member_offset_bytes = udm.offset // 8
            return member_offset_bytes
        
        return None
    except Exception as e:
        logging.error(f"_find_vtable_offset_for_function: Error finding vtable offset for function at {func_ea:#x}: {e}")
        import traceback
        traceback.print_exc()
        return None


def _get_function_eas_from_vtable_member(member_tid, vtable_tif, member_offset):
    """Get all function EAs referenced by a vtable member.
    
    Args:
        member_tid: TID of the vtable member
        vtable_tif: tinfo_t of the vtable struct
        member_offset: Offset of the member in bits
    
    Returns:
        list: List of function EAs
    """
    func_eas = []
    
    # Method 1: Get functions via DataRefsTo (member TID -> function EA)
    for ref_ea in idautils.DataRefsTo(member_tid):
        if utils.is_func(ref_ea):
            func_eas.append(ref_ea)
            logging.debug(f"_get_function_eas_from_vtable_member: Found function {hex(ref_ea)} via DataRefsTo")
    
    # Method 2: Try to get function EA from member comment
    # Comments are set in format: f"{func:08x}"
    member_offset_bytes = member_offset // 8
    member_cmt = idc.get_member_cmt(vtable_tif.get_tid(), member_offset_bytes, False)
    if member_cmt:
        try:
            func_ea = int(member_cmt, 16)
            if func_ea != BADADDR and utils.is_func(func_ea) and func_ea not in func_eas:
                func_eas.append(func_ea)
                logging.debug(f"_get_function_eas_from_vtable_member: Found function {hex(func_ea)} via member comment")
        except ValueError:
            pass
    
    # Method 3: Try to find function from vtable instance
    vtable_struct_name = vtable_tif.get_type_name()
    func_ea = _find_func_ea_from_vtable_instance(vtable_struct_name, member_offset)
    if func_ea and func_ea != BADADDR and func_ea not in func_eas:
        func_eas.append(func_ea)
        logging.debug(f"_get_function_eas_from_vtable_member: Found function {hex(func_ea)} via vtable instance")
    
    logging.info(f"_get_function_eas_from_vtable_member: Total {len(func_eas)} function(s) found for member_tid={hex(member_tid)}")
    return func_eas


def _process_related_class_functions(related_class_tif, member_offset,
                                       new_func_name, processed_functions, relation_label):
    """Process functions in a related class (superclass or subclass).
    
    Args:
        related_class_tif: tinfo_t of the related class to process
        member_offset: Offset of the member in bits
        new_func_name: New name for the function
        processed_functions: Set of function EAs already processed
        relation_label: Label for the relation (e.g., "superclass", "subclass")
    
    Returns:
        list: List of (func_ea, new_func_name) tuples for batch processing
    """
    func_rename_list = []
    related_class_name = related_class_tif.get_type_name()
    related_vtable_name = get_class_vtable_struct_name(related_class_name, 0)
    related_vtable_tif = ida_typeinf.tinfo_t(name=related_vtable_name)
    
    if not related_vtable_tif.is_udt():
        return func_rename_list
    
    related_member_idx, related_member = related_vtable_tif.get_udm_by_offset(member_offset)
    if related_member_idx == -1:
        return func_rename_list
    
    # Get the member TID
    related_member_tid = related_vtable_tif.get_udm_tid(related_member_idx)
    if related_member_tid == BADADDR:
        return func_rename_list
    
    # Get function EAs for this member
    related_func_eas = _get_function_eas_from_vtable_member(
        related_member_tid, related_vtable_tif, member_offset
    )
    
    for func_ea in related_func_eas:
        if func_ea in processed_functions:
            logging.debug(f"_process_related_class_functions: Skipping already processed function {hex(func_ea)}")
            continue
        processed_functions.add(func_ea)
        
        func_name = idc.get_name(func_ea)
        # Check if function already has the expected name to avoid infinite loops
        if func_name == new_func_name:
            logging.debug(f"_process_related_class_functions: Function {hex(func_ea)} already has name '{new_func_name}', skipping")
            continue
        
        func_rename_list.append((func_ea, new_func_name))
        logging.info(f"_process_related_class_functions: Will rename function {hex(func_ea)} from '{func_name}' to '{new_func_name}' ({relation_label})")
    
    logging.debug(f"_process_related_class_functions: Returning {len(func_rename_list)} function(s) to rename for {relation_label}")
    return func_rename_list


def update_vtable_struct(
    functions_ea,
    vtable_struct,
    class_name,
    this_type=None,
    get_next_func_callback=get_vtable_line,
    vtable_head=None,
    ignore_list=None,
    add_dummy_member=False,
    parent_name=None,
    add_func_this=True,
    force_rename_vtable_head=False,  # rename vtable head even if it is already named by IDA
    overwrite=False,                 # rename methods AND update this ptr type even if already been named / set
):
    # pylint: disable=too-many-arguments,too-many-locals,too-many-branches
    # TODO: refactor
    if this_type is None:
        this_type = utils.get_typeinf_ptr(class_name)
    if not add_func_this:
        this_type = None
    
    # Get parent vtable struct if parent_name is provided
    parent_vtable_struct = None
    if parent_name:
        parent_vtable_name = get_class_vtable_struct_name(parent_name, 0)
        parent_vtable_tif = ida_typeinf.tinfo_t(name=parent_vtable_name)
        if parent_vtable_tif.is_udt():
            parent_vtable_struct = parent_vtable_tif
    
    func, next_func = get_next_func_callback(
        functions_ea,
        ignore_list=ignore_list,
    )
    dummy_i = 1
    function_count = 0
    while func is not None:
        new_func_name = None
        new_field_name = None
        
        # If parent vtable exists, try to inherit member name from parent
        if parent_vtable_struct is not None:
            member_offset = function_count * utils.WORD_LEN * utils.BYTE_SIZE # Convert to bits
            parent_member_idx, parent_member = parent_vtable_struct.get_udm_by_offset(member_offset)
            if parent_member_idx != -1 and parent_member.name:
                parent_member_name = parent_member.name
                # Use parent name unless it's autogenerated
                if not is_autogenerated_func_name(parent_member_name):
                    new_field_name = parent_member_name # avoid double conversion
                    # Also rename the function to match the parent member name
                    new_func_name = fieldname2funcname(parent_member_name, class_name)

        new_func_name, _ = update_func_name_with_class(func, class_name, overwrite=overwrite, func_name=new_func_name)

        if new_field_name is None:
            new_field_name = funcname2fieldname(new_func_name)

        func_ptr = None
        if ida_hexrays.init_hexrays_plugin():
            fix_userpurge(func, ida_typeinf.TINFO_GUESSED)
            update_func_this(func, this_type, ida_typeinf.TINFO_GUESSED, overwrite=overwrite)
            func_ptr = utils.get_typeinf_ptr(utils.get_func_tinfo(func))
        else:
            func_ptr = make_funcptr_pt(func, this_type)  # TODO: maybe try to get or guess type?
        if add_dummy_member:
            utils.add_to_struct(vtable_struct, "dummy_%d" % dummy_i, func_ptr)
            dummy_i += 1
        if not func_ptr:
            func_ptr = ida_typeinf.tinfo_t("void (*)(void)")
        if function_count == 0:
            # We did an hack for vtables contained in union vtable with one dummy member
            _, ptr_member = utils.add_to_struct(
                vtable_struct, new_field_name, func_ptr, 0, overwrite=True
            )
        else:
            _, ptr_member = utils.add_to_struct(
                vtable_struct,
                new_field_name,
                func_ptr,
                function_count * utils.WORD_LEN * utils.BYTE_SIZE,
                is_offset=True,
                overwrite=True
            )
        if ptr_member is None:
            logging.error(
                "Couldn't add %s(%s) to vtable struct 0x%X at offset 0x%X",
                new_field_name,
                str(func_ptr),
                vtable_struct.get_tid(),
            )
        # Get the member TID to add a reference from the struct member to the function EA
        field_idx = vtable_struct.find_udm(ptr_member, 0)
        if field_idx != -1:
            member_tid = vtable_struct.get_udm_tid(field_idx)
            if member_tid != BADADDR:
                ida_xref.add_dref(member_tid, func, ida_xref.XREF_USER | ida_xref.dr_I)
            else:
                logging.warning(
                    "Couldn't get member TID for %s in vtable struct 0x%X",
                    new_field_name,
                    vtable_struct.get_tid(),
                )
        else:
            logging.warning(
                "Couldn't find member index for %s in vtable struct 0x%X",
                new_field_name,
                vtable_struct.get_tid(),
            )
        # Set comment on the member with the function EA
        if field_idx != -1:
            field_cmt = f"{func:08x}"
            vtable_struct.set_udm_cmt(field_idx, field_cmt, False)
        func, next_func = get_next_func_callback(
            next_func, ignore_list=ignore_list
        )
        function_count += 1

    vtable_size = vtable_struct.get_size()

    if vtable_head is None:
        vtable_head = functions_ea
    ida_bytes.del_items(vtable_head, ida_bytes.DELIT_SIMPLE, vtable_size)
    ida_bytes.create_struct(vtable_head, vtable_size, vtable_struct.get_tid())
    if parent_name is None and this_type:
        parent = utils.deref_struct_from_tinfo(this_type)
        parent_name = parent.get_type_name()
        if parent_name == class_name:
            parent_name = None
    utils.set_name_retry(vtable_head, get_vtable_instance_name(class_name, parent_name))


def is_valid_func_char(c):
    ALLOWED_CHARS = [":", "_"]
    return c.isalnum() or c in ALLOWED_CHARS


def find_valid_cppname_in_line(line, idx):
    end_idx = idx
    start_idx = idx
    if len(line) < idx:
        return None
    while start_idx >= 0 and is_valid_func_char(line[start_idx]):
        if line[start_idx] == ":":
            if line[start_idx - 1] == ":":
                start_idx -= 1
            else:
                break
        start_idx -= 1
    while end_idx < len(line) and is_valid_func_char(line[end_idx]):
        if line[end_idx] == ":":
            if line[end_idx + 1] == ":":
                end_idx += 1
            else:
                break
        end_idx += 1
    if end_idx > start_idx:
        return line[start_idx + 1 : end_idx]
    return None


def get_overriden_func_names(union_name, offset, get_not_funcs_members=False):
    sptr = utils.get_sptr_by_name(union_name)
    res = []
    if not sptr.is_union():
        return res

    for i in range(sptr.get_size()):
        idx, member = sptr.get_udm_by_offset(i)
        if member is None: # Added check for None
            continue
        cls = member.name
        tinfo = utils.get_member_tinfo(member)
        logging.debug("Trying %s", cls)
        if cls == get_interface_empty_vtable_name() or not tinfo.is_ptr():
            continue
        pointed_obj = tinfo.get_pointed_object()
        if not pointed_obj.is_struct():
            continue
        vtable_sptr = utils.get_sptr_by_name(pointed_obj.get_final_type_name())
        if vtable_sptr.get_size() <= offset:
            continue
        idx, funcptr_member = vtable_sptr.get_udm_by_offset(offset)
        if funcptr_member is None: # Added check for None
            continue
        funcptr_type = utils.get_member_tinfo(funcptr_member)
        func_name = funcptr_member.name
        if not funcptr_type.is_funcptr() and not get_not_funcs_members:
            continue
        res.append((cls, func_name))
    return res


def create_vtable_struct(sptr, name, vtable_offset, parent_name=None):
    logging.debug("create_vtable_struct(%s, 0x%X)", name, vtable_offset)
    vtable_details = find_vtable_at_offset(sptr, vtable_offset)
    parent_vtable_member = None
    parent_vtable_struct = None
    parents_chain = None
    if vtable_details is not None:
        logging.debug("Found parent vtable %s 0x%X", name, vtable_offset)
        (
            parent_vtable_member,
            parent_vtable_struct,
            parents_chain,
        ) = vtable_details
    else:
        logging.debug("Couldn't found parent vtable %s %d", name, vtable_offset)
    if parent_vtable_member is not None:
        parent_name = parent_vtable_struct.get_type_name()
    vtable_name = get_class_vtable_struct_name(name, vtable_offset)
    if vtable_offset == 0:
        this_type = utils.get_typeinf_ptr(name)
    else:
        this_type = utils.get_typeinf_ptr(parent_name)
    if vtable_name is None:
        logging.exception(
            "create_vtable_struct(%s, 0x%X): vtable_name is" " None",
            name,
            vtable_offset,
        )
    udt = ida_typeinf.udt_type_data_t()
    vtable_struct = utils.get_or_create_struct(vtable_name)
    if vtable_struct.get_tid() == BADADDR:
        logging.exception("Couldn't create struct %s", vtable_name)
#    if parents_chain:
#        for parent_name, offset in parents_chain:
#            add_child_vtable(parent_name, name, vtable_struct.get_tid(), offset * utils.BYTE_SIZE)
#    else:
    add_class_vtable(sptr, vtable_name, vtable_offset)

    return vtable_struct, this_type


# syntax sugar: make_struct("S40") creates struct of size 0x40
def make_struct(name, struct_size = None, parent_name = None):
    struc = utils.get_or_create_struct(name, parent_name=parent_name)

    if struct_size is None:
        if name.startswith("S"):
            struct_size = int(name[1:], 16)
        else:
            return 0

    cur_size = struc.get_size()
    if cur_size == 1 and struc.get_udm(0)[0] == -1:
        # empty struct get_size() returns 1
        cur_size = 0

    bt_int64 = ida_typeinf.tinfo_t(ida_typeinf.BT_INT64)
    bt_int32 = ida_typeinf.tinfo_t(ida_typeinf.BT_INT32)
    bt_int16 = ida_typeinf.tinfo_t(ida_typeinf.BT_INT16)
    bt_int08 = ida_typeinf.tinfo_t(ida_typeinf.BT_INT8)

    while cur_size < struct_size:
        field_name = "field_" + format(cur_size, "X")
        cur_offset = cur_size * utils.BYTE_SIZE

        if struct_size - cur_size >= 8 and utils.WORD_LEN == 8:
            r = utils.add_to_struct(struc, field_name, bt_int64, cur_offset)
            cur_size += 8

        elif struct_size - cur_size >= 4:
            r = utils.add_to_struct(struc, field_name, bt_int32, cur_offset)
            cur_size += 4

        elif struct_size - cur_size >= 2:
            r = utils.add_to_struct(struc, field_name, bt_int16, cur_offset)
            cur_size += 2

        elif struct_size - cur_size == 1:
            r = utils.add_to_struct(struc, field_name, bt_int08, cur_offset)
            cur_size += 1

        if not r:
            break
    return cur_size


def find_structs_by_size(size = None, min_size: int = 0, ignore_prefixes: list = []):
    """
    Enumerate all defined structures and filter those of a specified size.
    :param size: The size to filter structures by (in bytes).
    :return: A list of tuples (structure_name, structure_id, structure_size).
    """
    if size is None and min_size <= 0:
        raise ValueError("Either size or min_size must be specified")

    matching_structs = []

    # Iterate over all structures in IDA
    for idx in range(ida_struct.get_struc_qty()):
        sid = ida_struct.get_struc_by_idx(idx)
        if sid == BADADDR:
            continue

        struct = ida_struct.get_struc(sid)
        if not struct:
            continue

        # Check the size of the structure
        struct_size = ida_struct.get_struc_size(struct)
        if (size is None and struct_size >= min_size) or (size is not None and struct_size == size):
            name = ida_struct.get_struc_name(sid)
            if not any(name.startswith(prefix) for prefix in ignore_prefixes):
                matching_structs.append(name)

    return matching_structs

def make_vtable(
    class_name,
    struct_size=None,
    vtable_ea=None,
    vtable_ea_stop=None,
    offset_in_class=0,
    parent_name=None,
    add_func_this=True,
    _get_vtable_line=get_vtable_line,
    overwrite=False,
):
    if not vtable_ea and not vtable_ea_stop:
        vtable_ea, vtable_ea_stop = utils.get_selected_range_or_line()
    vtable_struct, this_type = create_vtable_struct(
        utils.get_or_create_struct(class_name, is_class=True, parent_name=parent_name),
        class_name,
        offset_in_class * utils.BYTE_SIZE,
        parent_name=parent_name
    )
    if struct_size:
        make_struct(class_name, struct_size)
    logging.info(f"{vtable_ea=}, {vtable_ea_stop=}, ")
    update_vtable_struct(
        vtable_ea,
        vtable_struct,
        class_name,
        this_type=this_type,
        get_next_func_callback=partial(_get_vtable_line, stop_ea=vtable_ea_stop),
        parent_name=parent_name,
        add_func_this=add_func_this,
        overwrite=overwrite,
    )


def add_baseclass(class_name, baseclass_name, baseclass_offset=0, to_refresh=False):
    member_name = get_base_member_name(baseclass_name, baseclass_offset)
    struct_ptr = utils.get_sptr_by_name(class_name)
    baseclass_ptr = utils.get_sptr_by_name(baseclass_name)
    if not struct_ptr or not baseclass_ptr:
        return False
    _, member = utils.add_to_struct(struct_ptr, member_name,
                                 member_type=utils.get_typeinf(baseclass_name),
                                 offset=baseclass_offset,
                                 overwrite=True)
    if not member:
        logging.debug(
            "add_baseclass(%s. %s): member not found",
            class_name,
            baseclass_name,
        )
        return False
    if to_refresh:
        utils.refresh_struct(struct_ptr)
    return True


@batchmode
def scan_all_vtables():
    """Scan all existing vtable structs and add missing references from members to function EAs.
    
    This function:
    1. Finds all structs that are vtables (by checking if name contains VTABLE_POSTFIX)
    2. For each vtable struct, iterates through all members
    3. For each member that has a comment with an EA, checks if a reference exists
    4. If no reference exists, adds a cross-reference from the member to the function EA
    
    Returns:
        tuple: (total_vtables_processed, total_references_added)
    """
    logging.info("Starting scan for missing vtable member references...")
    
    total_vtables_processed = 0
    total_references_added = 0
    
    # Iterate over all structures in IDA using idautils.Structs()
    for ordinal, sid, struct_name in idautils.Structs():
        if sid == BADADDR:
            continue
        
        # Get struct as tinfo_t to use our helper functions
        vtable_struct = ida_typeinf.tinfo_t()
        if not vtable_struct.get_type_by_tid(sid):
            continue
        
        # Check if this is a vtable struct
        if not is_struct_vtable(vtable_struct):
            continue
        
        # Get struct size - check for None or BADADDR
        struct_size = vtable_struct.get_size()
        if struct_size is None or struct_size == BADADDR or struct_size == 0:
            logging.debug("Skipping vtable struct %s: invalid size (%s)", struct_name, struct_size)
            continue
        
        total_vtables_processed += 1
        logging.debug("Processing vtable struct: %s (size: %d)", struct_name, struct_size)
        
        # Get all members using get_udt_details() - more reliable than iterating by offset
        udt = ida_typeinf.udt_type_data_t()
        if not vtable_struct.get_udt_details(udt):
            logging.debug("Could not get UDT details for %s", struct_name)
            continue
        
        # Iterate through all members
        for member_idx, member in enumerate(udt):
            try:
                # Skip gap members
                if member.is_gap():
                    continue
                
                # Get member ID using idc.get_member_id() - this is the same method IDA uses internally
                # Convert offset from bits to bytes for idc.get_member_id()
                struct_tid = vtable_struct.get_tid()
                member_offset_bytes = member.offset // utils.BYTE_SIZE
                member_tid = idc.get_member_id(struct_tid, member_offset_bytes)
                
                if member_tid == -1 or member_tid == BADADDR:
                    logging.debug(
                        "Could not get member ID for member %d (offset 0x%X bytes) in %s (struct_tid: 0x%X)",
                        member_idx,
                        member_offset_bytes,
                        struct_name,
                        struct_tid
                    )
                    continue
                
                # Check if member is a function pointer
                if not member.type.is_funcptr():
                    continue
                
                # Try to get the function EA from the member comment
                # Comments are set in format: f"{func:08x}"
                # Try to get comment from udm_t object first, then fallback to idc.get_member_cmt()
                member_cmt = None
                if hasattr(member, 'cmt') and member.cmt:
                    member_cmt = member.cmt
                else:
                    # Fallback: use idc.get_member_cmt() with struct TID and member offset
                    member_offset_bytes = member.offset // utils.BYTE_SIZE
                    member_cmt = idc.get_member_cmt(vtable_struct.get_tid(), member_offset_bytes, False)
                
                func_ea = None
                
                if member_cmt:
                    # Try to parse the EA from the comment (format: "08x" hex string)
                    try:
                        func_ea = int(member_cmt, 16)
                        if func_ea == 0 or func_ea == BADADDR:
                            func_ea = None
                    except (ValueError, TypeError):
                        pass
                
                # If we don't have an EA from comment, try to find vtable instance
                # and read the function pointer from memory
                if func_ea is None:
                    func_ea = _find_func_ea_from_vtable_instance(struct_name, member.offset)
                
                if func_ea is None or func_ea == BADADDR:
                    continue
                
                # Verify member_tid is actually a member ID (not a struct ID or other type)
                # Member IDs should be valid and point to a struct member
                if not idc.is_member_id(member_tid):
                    logging.warning(
                        "member_tid 0x%X for %s.%s is not a valid member ID, skipping",
                        member_tid,
                        struct_name,
                        member.name if member.name else f"offset_{member.offset}"
                    )
                    continue
                
                # Always delete any existing xref first to ensure we create a fresh, correct one
                # This fixes cases where xrefs were created with incorrect member_tid
                ida_xref.del_dref(member_tid, func_ea)
                
                # Add the correct reference from the member to the function
                if ida_xref.add_dref(member_tid, func_ea, ida_xref.XREF_USER | ida_xref.dr_I):
                        total_references_added += 1
                        logging.debug(
                            "Added xref from %s.%s (offset 0x%X) to function at 0x%X",
                            struct_name,
                            member.name if member.name else f"offset_{member.offset}",
                            member.offset,
                            func_ea
                        )
                else:
                    logging.warning(
                        "Failed to add xref from %s.%s to 0x%X",
                        struct_name,
                        member.name if member.name else f"offset_{member.offset}",
                        func_ea
                    )
                    
            except Exception as e:
                logging.exception(
                    "Error processing member %d (offset 0x%X) in vtable struct %s: %s",
                    member_idx,
                    member.offset if member else 0,
                    struct_name,
                    e
                )
                continue
    
    logging.info(
        "Completed scan: processed %d vtable structs, added %d missing references",
        total_vtables_processed,
        total_references_added
    )
    
    return total_vtables_processed, total_references_added


def _find_func_ea_from_vtable_instance(vtable_struct_name, member_offset):
    """Try to find the function EA by locating a vtable instance and reading the pointer.
    
    Args:
        vtable_struct_name: Name of the vtable struct
        member_offset: Offset of the member in the struct (in bits, need to convert to bytes)
    
    Returns:
        Function EA if found, None otherwise
    """
    # Extract class name from vtable struct name (remove VTABLE_POSTFIX)
    if VTABLE_POSTFIX not in vtable_struct_name:
        return None
    
    class_name = vtable_struct_name.replace(VTABLE_POSTFIX, "")
    # Handle offset-based vtable names like "Class_0004_vtbl"
    if "_" in class_name:
        parts = class_name.rsplit("_", 1)
        if len(parts) == 2 and len(parts[1]) == 4:
            try:
                int(parts[1], 16)  # Check if it's a hex offset
                class_name = parts[0]
            except ValueError:
                pass
    
    # Try to find vtable instance by name
    vtable_instance_name = get_vtable_instance_name(class_name)
    vtable_ea = ida_name.get_name_ea(BADADDR, vtable_instance_name)
    
    if vtable_ea == BADADDR:
        # Try with parent name variations
        # This is a best-effort approach
        return None
    
    # Convert member offset from bits to bytes
    member_offset_bytes = member_offset // utils.BYTE_SIZE
    
    # Read the function pointer from the vtable instance
    try:
        func_ea = utils.get_ptr(vtable_ea + member_offset_bytes)
        if func_ea and func_ea != BADADDR:
            # Adjust for ARM thumb mode if needed
            if not utils.is_func(func_ea):
                func_ea -= 1
                if not utils.is_func(func_ea):
                    return None
            return func_ea
    except Exception:
        pass
    
    return None
